"""empty message

Revision ID: f717fffe10c3
Revises: 2eceb70750e8
Create Date: 2023-04-07 01:14:24.988493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f717fffe10c3'
down_revision = '2eceb70750e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_end', sa.Date(), nullable=True))
        batch_op.drop_column('data_end')
        batch_op.drop_column('data_start')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_start', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('data_end', sa.DATE(), nullable=True))
        batch_op.drop_column('date_end')
        batch_op.drop_column('date_start')

    # ### end Alembic commands ###
